<?php

use App\Http\Controllers\AccountActivityController;
use App\Http\Controllers\AccountActivityExportController;
use App\Http\Controllers\AccountingController;
use App\Http\Controllers\AccountingDimensionsController;
use App\Http\Controllers\AgreementController;
use App\Http\Controllers\AmcController;
use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\ApprovalsInboxController;
use App\Http\Controllers\BankReconciliationController;
use App\Http\Controllers\BrokerageController;
use App\Http\Controllers\ComplianceDocumentController;
use App\Http\Controllers\ConstructionController;
use App\Http\Controllers\CorporateTaxReturnController;
use App\Http\Controllers\CrmActivityController;
use App\Http\Controllers\CrmAssignmentController;
use App\Http\Controllers\CrmAutomationController;
use App\Http\Controllers\CrmCatalogController;
use App\Http\Controllers\CrmCompanyController;
use App\Http\Controllers\CrmContactController;
use App\Http\Controllers\CrmCustomFieldController;
use App\Http\Controllers\CrmDealController;
use App\Http\Controllers\CrmHierarchyController;
use App\Http\Controllers\CrmLeadController;
use App\Http\Controllers\CrmLeadExportController;
use App\Http\Controllers\CrmLeadImportController;
use App\Http\Controllers\CrmLeadPreferenceController;
use App\Http\Controllers\CrmLeadRequirementController;
use App\Http\Controllers\CrmPageController;
use App\Http\Controllers\CrmPipelineController;
use App\Http\Controllers\CrmPipelineReportController;
use App\Http\Controllers\CrmSettingsDataController;
use App\Http\Controllers\CustomerCreditNoteController;
use App\Http\Controllers\CustomerPortalController;
use App\Http\Controllers\CustomerRefundController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\DocumentVersionController;
use App\Http\Controllers\FinanceAuditTrailController;
use App\Http\Controllers\FinancialStatementsController;
use App\Http\Controllers\FixedAssetController;
use App\Http\Controllers\FleetController;
use App\Http\Controllers\GaimController;
use App\Http\Controllers\GlobalSearchController;
use App\Http\Controllers\HandoverController;
use App\Http\Controllers\InternalChatController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\InventoryImportController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\JobSlaController;
use App\Http\Controllers\JournalRegisterController;
use App\Http\Controllers\LeaseComplianceController;
use App\Http\Controllers\LegacyJournalMappingController;
use App\Http\Controllers\ListingController;
use App\Http\Controllers\LocaleController;
use App\Http\Controllers\MaintenanceJobCardController;
use App\Http\Controllers\MaintenanceRequestController;
use App\Http\Controllers\MarketingDemoRequestController;
use App\Http\Controllers\MatchmakerController;
use App\Http\Controllers\MetaLeadWebhookController;
use App\Http\Controllers\OffPlanController;
use App\Http\Controllers\OperatingBudgetController;
use App\Http\Controllers\OperationsExportController;
use App\Http\Controllers\OperationsOverviewController;
use App\Http\Controllers\OperationsReportController;
use App\Http\Controllers\OrganizationActivityController;
use App\Http\Controllers\OrganizationController;
use App\Http\Controllers\OrganizationNotificationController;
use App\Http\Controllers\OutstandingBalancesController;
use App\Http\Controllers\OwnerStatementController;
use App\Http\Controllers\PeriodCloseReadinessController;
use App\Http\Controllers\PortalMarketingController;
use App\Http\Controllers\PreventiveMaintenanceController;
use App\Http\Controllers\PrivateReportsController;
use App\Http\Controllers\ProcurementController;
use App\Http\Controllers\PropertyProfitabilityController;
use App\Http\Controllers\PublicListingController;
use App\Http\Controllers\QualifiedLeadController;
use App\Http\Controllers\ReadTokenController;
use App\Http\Controllers\RealEstatePartyController;
use App\Http\Controllers\RecordSearchController;
use App\Http\Controllers\ReferenceConfigurationController;
use App\Http\Controllers\ReferenceWorkflowController;
use App\Http\Controllers\RentInvoiceLinkController;
use App\Http\Controllers\ReservationController;
use App\Http\Controllers\SidebarReportsController;
use App\Http\Controllers\SignatureRequestController;
use App\Http\Controllers\SparePartsController;
use App\Http\Controllers\StaffServicesController;
use App\Http\Controllers\StyleguideController;
use App\Http\Controllers\VatReturnController;
use App\Http\Controllers\VendorBillController;
use App\Http\Controllers\VendorCashRefundController;
use App\Http\Controllers\VendorCreditNoteController;
use App\Http\Controllers\WorkTaskController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/dashboard')->name('home');
Route::post('demo', MarketingDemoRequestController::class)->middleware('throttle:5,1')->name('marketing.demo.store');
Route::get('webhooks/meta/leadgen', [MetaLeadWebhookController::class, 'verify'])->name('webhooks.meta.verify');
Route::post('webhooks/meta/leadgen', [MetaLeadWebhookController::class, 'receive'])->name('webhooks.meta.receive');
Route::get('webhooks/meta/pages/{webhookKey}/leadgen', [MetaLeadWebhookController::class, 'verifyPage'])->name('webhooks.meta.page.verify');
Route::post('webhooks/meta/pages/{webhookKey}/leadgen', [MetaLeadWebhookController::class, 'receivePage'])->name('webhooks.meta.page.receive');
Route::get('listings/{token}', [PublicListingController::class, 'show'])->name('public.listings.show');
Route::post('listings/{token}/inquiries', [PublicListingController::class, 'inquire'])->middleware('throttle:10,1')->name('public.listings.inquiries.store');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('portal', [CustomerPortalController::class, 'index'])->name('portal.index');
    Route::get('portal/invitations/{token}', [CustomerPortalController::class, 'invitation'])->middleware('throttle:20,1')->name('portal.invitation');
    Route::post('portal/invitations/{token}/accept', [CustomerPortalController::class, 'accept'])->middleware('throttle:20,1')->name('portal.accept');
    Route::get('portal/{grant}', [CustomerPortalController::class, 'show'])->name('portal.show');
    Route::post('portal/{grant}/service-requests', [CustomerPortalController::class, 'service'])->middleware('throttle:20,1')->name('portal.service');
    Route::get('organization/activity', OrganizationActivityController::class)->name('organization.activity');
    Route::get('organization/portal-access', [CustomerPortalController::class, 'manage'])->name('portal.manage');
    Route::post('organization/portal-access/invitations', [CustomerPortalController::class, 'invite'])->name('portal.invite');
    Route::post('organization/portal-access/invitations/{invitation}/revoke', [CustomerPortalController::class, 'revoke'])->name('portal.revoke');
    Route::post('organization/portal-access/invoices/{link}/revoke', [CustomerPortalController::class, 'revokeInvoice'])->name('portal.revoke-invoice');
    Route::post('organization/portal-access/invoices', [CustomerPortalController::class, 'linkInvoice'])->name('portal.link-invoice');
    Route::get('dashboard', DashboardController::class)->name('dashboard');
    Route::get('chat', [InternalChatController::class, 'index'])->name('chat.index');
    Route::post('chat/direct', [InternalChatController::class, 'direct'])->middleware('throttle:30,1')->name('chat.direct');
    Route::post('chat/group', [InternalChatController::class, 'group'])->middleware('throttle:20,1')->name('chat.group');
    Route::get('chat/rooms/{room}/messages', [InternalChatController::class, 'messages'])->middleware('throttle:120,1')->name('chat.messages');
    Route::post('chat/rooms/{room}/messages', [InternalChatController::class, 'send'])->middleware('throttle:60,1')->name('chat.send');
    Route::post('chat/rooms/{room}/read', [InternalChatController::class, 'read'])->middleware('throttle:240,1')->name('chat.read');
    Route::post('chat/rooms/{room}/attachments', [InternalChatController::class, 'attach'])->middleware('throttle:30,1')->name('chat.attach');
    Route::get('chat/attachments/{attachment}', [InternalChatController::class, 'attachment'])->middleware('throttle:240,1')->name('chat.attachments.show');
    Route::get('chat/rooms/{room}/call', [InternalChatController::class, 'activeCall'])->middleware('throttle:120,1')->name('chat.calls.active');
    Route::post('chat/rooms/{room}/call', [InternalChatController::class, 'startCall'])->middleware('throttle:20,1')->name('chat.calls.start');
    Route::get('chat/calls/{call}/signals', [InternalChatController::class, 'signals'])->middleware('throttle:300,1')->name('chat.calls.signals');
    Route::post('chat/calls/{call}/signals', [InternalChatController::class, 'signal'])->middleware('throttle:300,1')->name('chat.calls.signal');
    Route::post('chat/calls/{call}/end', [InternalChatController::class, 'endCall'])->middleware('throttle:30,1')->name('chat.calls.end');
    Route::get('chat/export', [InternalChatController::class, 'export'])->name('chat.export');
    Route::get('approvals', ApprovalsInboxController::class)->name('approvals.index');
    Route::get('tasks', [WorkTaskController::class, 'index'])->name('tasks.index');
    Route::post('tasks', [WorkTaskController::class, 'store'])->name('tasks.store');
    Route::put('tasks/{task}', [WorkTaskController::class, 'update'])->name('tasks.update');
    Route::post('tasks/{task}/complete', [WorkTaskController::class, 'complete'])->name('tasks.complete');
    Route::get('meetings', [AppointmentController::class, 'index'])->name('meetings.index');
    Route::post('meetings', [AppointmentController::class, 'store'])->name('meetings.store');
    Route::post('meetings/{appointment}/outcome', [AppointmentController::class, 'outcome'])->name('meetings.outcome');
    Route::get('real-estate/off-plan', [OffPlanController::class, 'index'])->name('offplan.index');
    Route::get('real-estate/off-plan/{project}', [OffPlanController::class, 'show'])->name('offplan.show');
    Route::post('real-estate/off-plan/projects', [OffPlanController::class, 'storeProject'])->name('offplan.projects.store');
    Route::post('real-estate/off-plan/{project}/units', [OffPlanController::class, 'storeUnit'])->name('offplan.units.store');
    Route::post('real-estate/off-plan/{project}/milestones', [OffPlanController::class, 'storeMilestone'])->name('offplan.milestones.store');
    Route::post('real-estate/off-plan/deals', [OffPlanController::class, 'storeDeal'])->name('offplan.deals.store');
    Route::post('real-estate/off-plan/deals/{deal}/status', [OffPlanController::class, 'status'])->name('offplan.deals.status');
    Route::get('marketing/portals', [PortalMarketingController::class, 'index'])->name('marketing.portals.index');
    Route::post('marketing/campaigns', [PortalMarketingController::class, 'campaign'])->name('marketing.campaigns.store');
    Route::post('marketing/publications', [PortalMarketingController::class, 'publication'])->name('marketing.publications.store');
    Route::post('marketing/publications/{publication}/enquiries', [PortalMarketingController::class, 'enquiry'])->name('marketing.enquiries.store');
    Route::get('marketing/subscriptions', [PortalMarketingController::class, 'subscriptions'])->name('marketing.subscriptions.index');
    Route::post('marketing/subscriptions', [PortalMarketingController::class, 'subscription'])->name('marketing.subscriptions.store');
    Route::post('marketing/subscriptions/{subscription}/bills', [PortalMarketingController::class, 'subscriptionBill'])->name('marketing.subscription-bills.store');
    Route::post('marketing/subscriptions/{subscription}/credits', [PortalMarketingController::class, 'subscriptionCredits'])->name('marketing.subscription-credits.store');
    Route::get('marketing/costing', [PortalMarketingController::class, 'costing'])->name('marketing.costing.index');
    Route::post('marketing/costing', [PortalMarketingController::class, 'spend'])->name('marketing.costing.store');
    Route::get('crm/matchmaker', [MatchmakerController::class, 'index'])->name('crm.matchmaker.index');
    Route::get('crm/matchmaker/leads/{lead}', [MatchmakerController::class, 'show'])->name('crm.matchmaker.show');
    Route::put('crm/matchmaker/leads/{lead}/preference', [MatchmakerController::class, 'preference'])->name('crm.matchmaker.preference');
    Route::put('real-estate/listings/{listing}/market-segment', [ListingController::class, 'updateMarketSegment'])->name('listings.market-segment.update');
    Route::get('hr', [StaffServicesController::class, 'index'])->name('hr.index');
    Route::get('hr/staff/{staff}', [StaffServicesController::class, 'show'])->name('hr.staff.show');
    Route::post('hr/staff', [StaffServicesController::class, 'staff'])->name('hr.staff.store');
    Route::post('hr/staff/{staff}/dismiss', [StaffServicesController::class, 'dismiss'])->name('hr.staff.dismiss');
    Route::post('hr/staff/{staff}/documents', [StaffServicesController::class, 'document'])->name('hr.documents.store');
    Route::post('hr/staff/{staff}/leave', [StaffServicesController::class, 'leave'])->name('hr.leave.store');
    Route::post('hr/leave/{leave}/decide', [StaffServicesController::class, 'decide'])->name('hr.leave.decide');
    Route::get('compliance/gaim', [GaimController::class, 'index'])->name('gaim.index');
    Route::post('compliance/gaim/rules', [GaimController::class, 'rule'])->name('gaim.rules.store');
    Route::post('compliance/gaim/records', [GaimController::class, 'record'])->name('gaim.records.store');
    Route::post('compliance/gaim/records/sync', [GaimController::class, 'sync'])->name('gaim.records.sync');
    Route::post('compliance/gaim/records/{record}/status', [GaimController::class, 'status'])->name('gaim.records.status');
    Route::get('compliance/gaim/bulletins', [GaimController::class, 'bulletins'])->name('gaim.bulletins.index');
    Route::post('compliance/gaim/bulletins', [GaimController::class, 'bulletin'])->name('gaim.bulletins.store');
    Route::post('compliance/gaim/bulletins/{bulletin}/publish', [GaimController::class, 'publish'])->name('gaim.bulletins.publish');
    Route::get('crm/broker-performance', [SidebarReportsController::class, 'brokerPerformance'])->name('crm.broker-performance');
    Route::get('transactions/pdc', [SidebarReportsController::class, 'pdc'])->name('transactions.pdc');
    Route::get('reports', [SidebarReportsController::class, 'reports'])->name('reports.index');
    Route::get('crm/lead-gateway', [SidebarReportsController::class, 'leadGateway'])->name('crm.lead-gateway');
    Route::get('crm/follow-up-settings', [SidebarReportsController::class, 'followUpSettings'])->name('crm.follow-up-settings');
    Route::get('styleguide', StyleguideController::class)->name('styleguide');
    Route::get('crm/assignment', [CrmAssignmentController::class, 'index'])->name('crm.assignment.index');
    Route::post('crm/assignment/check-in', [CrmAssignmentController::class, 'checkIn'])->name('crm.assignment.check-in');
    Route::put('crm/assignment/timezone', [CrmAssignmentController::class, 'setTimezone'])->name('crm.assignment.timezone');
    Route::put('crm/assignment/follow-up-reminder', [CrmAssignmentController::class, 'setFollowUpReminder'])->name('crm.assignment.follow-up-reminder');
    Route::put('crm/assignment/follow-up-escalation', [CrmAssignmentController::class, 'setFollowUpEscalation'])->name('crm.assignment.follow-up-escalation');
    Route::post('crm/assignment/quota', [CrmAssignmentController::class, 'setQuota'])->name('crm.assignment.quota');
    Route::post('crm/assignment/routes', [CrmAssignmentController::class, 'saveRoute'])->name('crm.assignment.routes.store');
    Route::put('crm/assignment/routes/{route}', [CrmAssignmentController::class, 'saveRoute'])->name('crm.assignment.routes.update');
    Route::delete('crm/assignment/routes/{route}', [CrmAssignmentController::class, 'deleteRoute'])->name('crm.assignment.routes.destroy');
    Route::post('crm/assignment/retry', [CrmAssignmentController::class, 'retry'])->name('crm.assignment.retry');
    Route::post('crm/assignment/meta-pages', [CrmAssignmentController::class, 'saveMetaPage'])->name('crm.assignment.meta-pages.store');
    Route::post('crm/assignment/meta-pages/{page}/subscribe', [CrmAssignmentController::class, 'subscribeMetaPage'])->name('crm.assignment.meta-pages.subscribe');
    Route::post('crm/assignment/meta-imports/{import}/retry', [CrmAssignmentController::class, 'retryMetaImport'])->name('crm.assignment.meta-imports.retry');
    Route::get('search', GlobalSearchController::class)->name('search.index');
    Route::get('api/records/search', RecordSearchController::class)->name('records.search');
    Route::get('notifications', [OrganizationNotificationController::class, 'index'])->name('notifications.index');
    Route::put('notifications/preferences', [OrganizationNotificationController::class, 'updatePreferences'])->name('notifications.preferences.update');
    Route::post('notifications/{notification}/read', [OrganizationNotificationController::class, 'markRead'])->name('notifications.read');
    Route::post('notifications/read-all', [OrganizationNotificationController::class, 'markAllRead'])->name('notifications.read-all');
    Route::get('reservations', [ReservationController::class, 'index'])->name('reservations.index');
    Route::post('reservations', [ReservationController::class, 'store'])->name('reservations.store');
    Route::get('lease-compliance', [LeaseComplianceController::class, 'index'])->name('lease-compliance.index');
    Route::post('lease-compliance/leases/{lease}/security-deposit', [LeaseComplianceController::class, 'storeDeposit'])->name('lease-compliance.deposits.store');
    Route::post('lease-compliance/leases/{lease}/cheques', [LeaseComplianceController::class, 'storeCheque'])->name('lease-compliance.cheques.store');
    Route::post('lease-compliance/leases/{lease}/service-charges', [LeaseComplianceController::class, 'storeServiceCharge'])->name('lease-compliance.service-charges.store');
    Route::post('lease-compliance/leases/{lease}/ejari', [LeaseComplianceController::class, 'storeEjari'])->name('lease-compliance.ejari.store');
    Route::post('lease-compliance/ejari/{registration}/register', [LeaseComplianceController::class, 'registerEjari'])->name('lease-compliance.ejari.register');
    Route::post('lease-compliance/ejari/{registration}/renew', [LeaseComplianceController::class, 'renewEjari'])->name('lease-compliance.ejari.renew');
    Route::post('lease-compliance/deposits/{deposit}/settlement', [LeaseComplianceController::class, 'storeDepositSettlement'])->name('lease-compliance.deposit-settlements.store');
    Route::post('lease-compliance/deposit-settlements/{settlement}/deductions', [LeaseComplianceController::class, 'storeDepositDeduction'])->name('lease-compliance.deposit-settlements.deductions.store');
    Route::post('lease-compliance/deposit-settlements/{settlement}/submit', [LeaseComplianceController::class, 'submitDepositSettlement'])->name('lease-compliance.deposit-settlements.submit');
    Route::post('lease-compliance/deposit-settlements/{settlement}/approve', [LeaseComplianceController::class, 'approveDepositSettlement'])->name('lease-compliance.deposit-settlements.approve');
    Route::post('lease-compliance/deposit-settlements/{settlement}/post-refund', [LeaseComplianceController::class, 'postDepositRefund'])->name('lease-compliance.deposit-settlements.post-refund');
    Route::post('lease-compliance/deposit-deductions/{deduction}/post-rent-offset', [LeaseComplianceController::class, 'postRentOffset'])->name('lease-compliance.deposit-deductions.post-rent-offset');
    Route::post('lease-compliance/deposit-deductions/{deduction}/reverse-rent-offset', [LeaseComplianceController::class, 'reverseRentOffset'])->name('lease-compliance.deposit-deductions.reverse-rent-offset');
    Route::post('lease-compliance/deposit-deductions/{deduction}/post-recovery', [LeaseComplianceController::class, 'postRecovery'])->name('lease-compliance.deposit-deductions.post-recovery');
    Route::post('lease-compliance/deposit-deductions/{deduction}/post-forfeiture', [LeaseComplianceController::class, 'postForfeiture'])->name('lease-compliance.deposit-deductions.post-forfeiture');
    Route::post('lease-compliance/cheques/{cheque}/{action}', [LeaseComplianceController::class, 'updateCheque'])->name('lease-compliance.cheques.update');
    Route::get('agreements', [AgreementController::class, 'index'])->name('agreements.index');
    Route::post('agreements/leases', [AgreementController::class, 'storeLease'])->name('agreements.leases.store');
    Route::post('agreements/leases/{lease}/activate', [AgreementController::class, 'activateLease'])->name('agreements.leases.activate');
    Route::post('agreements/leases/{lease}/renew', [AgreementController::class, 'renewLease'])->name('agreements.leases.renew');
    Route::post('agreements/sales-contracts', [AgreementController::class, 'storeSalesContract'])->name('agreements.sales-contracts.store');
    Route::post('agreements/sales-contracts/{salesContract}/activate', [AgreementController::class, 'activateSalesContract'])->name('agreements.sales-contracts.activate');
    Route::get('handovers', [HandoverController::class, 'index'])->name('handovers.index');
    Route::post('handovers', [HandoverController::class, 'store'])->name('handovers.store');
    Route::post('handovers/{handover}/complete', [HandoverController::class, 'complete'])->name('handovers.complete');
    Route::post('handovers/{handover}/inspection-items', [HandoverController::class, 'storeInspection'])->name('handovers.inspection-items.store');
    Route::post('handover-inspection-items/{inspectionItem}/evidence', [HandoverController::class, 'storeInspectionEvidence'])->name('handovers.inspection-items.evidence.store');
    Route::get('handover-inspection-evidence/{document}/download', [HandoverController::class, 'downloadInspectionEvidence'])->name('handovers.inspection-items.evidence.download');
    Route::put('vacancies/{vacancy}', [HandoverController::class, 'updateVacancy'])->name('vacancies.update');
    Route::post('invoices/{invoice}/credit-notes', [CustomerCreditNoteController::class, 'store'])->name('credit-notes.store');
    Route::post('credit-notes/{creditNote}/post', [CustomerCreditNoteController::class, 'post'])->name('credit-notes.post');
    Route::post('credit-notes/{creditNote}/reverse', [CustomerCreditNoteController::class, 'reverse'])->name('credit-notes.reverse');
    Route::post('invoices/{invoice}/refunds', [CustomerRefundController::class, 'store'])->name('customer-refunds.store');
    Route::post('customer-refunds/{refund}/approve', [CustomerRefundController::class, 'approve'])->name('customer-refunds.approve');
    Route::post('customer-refunds/{refund}/reject', [CustomerRefundController::class, 'reject'])->name('customer-refunds.reject');
    Route::post('customer-refunds/{refund}/reverse', [CustomerRefundController::class, 'reverse'])->name('customer-refunds.reverse');
    Route::post('invoices', [InvoiceController::class, 'store'])->name('invoices.store');
    Route::put('invoices/{invoice}/accounting-treatment', [InvoiceController::class, 'updateTreatment'])->name('invoices.treatment.update');
    Route::get('invoices', [InvoiceController::class, 'index'])->name('invoices.index');
    Route::post('invoices/{invoice}/post', [InvoiceController::class, 'post'])->name('invoices.post');
    Route::post('invoices/{invoice}/payments', [InvoiceController::class, 'pay'])->name('invoices.pay');
    Route::get('finance/vendor-cash-refunds', [VendorCashRefundController::class, 'index'])->name('vendor-refunds.index');
    Route::post('finance/vendor-cash-refunds/bills/{bill}', [VendorCashRefundController::class, 'store'])->name('vendor-refunds.store');
    Route::post('finance/vendor-cash-refunds/{refund}/approve', [VendorCashRefundController::class, 'approve'])->name('vendor-refunds.approve');
    Route::post('finance/vendor-cash-refunds/{refund}/reject', [VendorCashRefundController::class, 'reject'])->name('vendor-refunds.reject');
    Route::post('finance/vendor-cash-refunds/{refund}/reverse', [VendorCashRefundController::class, 'reverse'])->name('vendor-refunds.reverse');
    Route::get('vendor-bills', [VendorBillController::class, 'index'])->name('vendor-bills.index');
    Route::get('accounting', [AccountingController::class, 'index'])->name('accounting.index');
    Route::get('accounting/dimensions', [AccountingDimensionsController::class, 'index'])->name('accounting.dimensions.index');
    Route::post('accounting/dimensions/{level}', [AccountingDimensionsController::class, 'store'])->name('accounting.dimensions.store');
    Route::get('accounting/legacy-mappings', [LegacyJournalMappingController::class, 'index'])->name('accounting.legacy-mappings.index');
    Route::post('accounting/legacy-mappings', [LegacyJournalMappingController::class, 'store'])->name('accounting.legacy-mappings.store');
    Route::put('accounting/legacy-mappings/approvers', [LegacyJournalMappingController::class, 'delegate'])->name('accounting.legacy-mappings.delegate');
    Route::post('accounting/legacy-mappings/{mapping}/decide', [LegacyJournalMappingController::class, 'decide'])->name('accounting.legacy-mappings.decide');
    Route::post('accounting/legacy-mappings/{mapping}/reverse', [LegacyJournalMappingController::class, 'reverse'])->name('accounting.legacy-mappings.reverse');
    Route::get('accounting/activity', AccountActivityController::class)->name('accounting.activity');
    Route::get('accounting/activity.csv', AccountActivityExportController::class)->name('accounting.activity.export');
    Route::get('accounting/journal-register', [JournalRegisterController::class, 'index'])->name('accounting.journal-register');
    Route::get('accounting/journal-register.csv', [JournalRegisterController::class, 'export'])->name('accounting.journal-register.export');
    Route::get('accounting/audit-trail', [FinanceAuditTrailController::class, 'index'])->name('accounting.audit-trail');
    Route::get('accounting/audit-trail.csv', [FinanceAuditTrailController::class, 'export'])->name('accounting.audit-trail.export');
    Route::get('accounting/fixed-assets', [FixedAssetController::class, 'index'])->name('accounting.fixed-assets.index');
    Route::get('accounting/fixed-assets/review-readiness.csv', [FixedAssetController::class, 'exportReviewReadiness'])->name('accounting.fixed-assets.review-readiness.export');
    Route::post('accounting/fixed-assets', [FixedAssetController::class, 'store'])->name('accounting.fixed-assets.store');
    Route::post('accounting/fixed-assets/{asset}/dispose', [FixedAssetController::class, 'dispose'])->name('accounting.fixed-assets.dispose');
    Route::post('accounting/fixed-assets/{asset}/transfer', [FixedAssetController::class, 'transfer'])->name('accounting.fixed-assets.transfers.store');
    Route::post('accounting/fixed-assets/{asset}/disposal/post', [FixedAssetController::class, 'postDisposal'])->name('accounting.fixed-assets.disposals.post');
    Route::post('accounting/fixed-assets/disposals/{disposal}/reverse', [FixedAssetController::class, 'reverseDisposal'])->name('accounting.fixed-assets.disposals.reverse');
    Route::post('accounting/fixed-assets/reviews/{review}/impairment', [FixedAssetController::class, 'postImpairment'])->name('accounting.fixed-assets.impairments.post');
    Route::post('accounting/fixed-assets/impairments/{impairment}/reverse', [FixedAssetController::class, 'reverseImpairment'])->name('accounting.fixed-assets.impairments.reverse');
    Route::post('accounting/fixed-assets/{asset}/reviews', [FixedAssetController::class, 'storeReview'])->name('accounting.fixed-assets.reviews.store');
    Route::post('accounting/fixed-assets/reviews/{review}/estimate-change', [FixedAssetController::class, 'approveEstimateChange'])->name('accounting.fixed-assets.estimate-changes.store');
    Route::post('accounting/fixed-assets/depreciation', [FixedAssetController::class, 'postDepreciation'])->name('accounting.fixed-assets.depreciation.post');
    Route::post('accounting/fixed-assets/depreciation/{depreciation}/reverse', [FixedAssetController::class, 'reverseDepreciation'])->name('accounting.fixed-assets.depreciation.reverse');
    Route::get('accounting/budgets', OperatingBudgetController::class)->name('accounting.budgets');
    Route::get('accounting/budgets.csv', [OperatingBudgetController::class, 'export'])->name('accounting.budgets.export');
    Route::post('accounting/budgets', [OperatingBudgetController::class, 'store'])->name('accounting.budgets.store');
    Route::put('accounting/budgets/{budget}/accounts', [OperatingBudgetController::class, 'saveAccount'])->name('accounting.budgets.accounts.save');
    Route::delete('accounting/budgets/{budget}/accounts/{account}', [OperatingBudgetController::class, 'removeAccount'])->name('accounting.budgets.accounts.remove');
    Route::put('accounting/budgets/{budget}/effective-month', [OperatingBudgetController::class, 'rebase'])->name('accounting.budgets.rebase');
    Route::post('accounting/budgets/{budget}/submit', [OperatingBudgetController::class, 'submit'])->name('accounting.budgets.submit');
    Route::post('accounting/budgets/{budget}/approve', [OperatingBudgetController::class, 'approve'])->name('accounting.budgets.approve');
    Route::post('accounting/budgets/{budget}/reject', [OperatingBudgetController::class, 'reject'])->name('accounting.budgets.reject');
    Route::get('accounting/statements', FinancialStatementsController::class)->name('accounting.statements');
    Route::get('accounting/statements/balance-sheet.csv', [FinancialStatementsController::class, 'exportBalanceSheet'])->name('accounting.statements.balance-sheet.export');
    Route::get('accounting/statements/profit-and-loss.csv', [FinancialStatementsController::class, 'exportProfitAndLoss'])->name('accounting.statements.profit-and-loss.export');
    Route::get('accounting/outstanding-balances', OutstandingBalancesController::class)->name('accounting.outstanding-balances');
    Route::get('accounting/outstanding-balances.csv', [OutstandingBalancesController::class, 'export'])->name('accounting.outstanding-balances.export');
    Route::get('accounting/corporate-tax', [CorporateTaxReturnController::class, 'index'])->name('accounting.corporate-tax');
    Route::get('accounting/corporate-tax.csv', [CorporateTaxReturnController::class, 'export'])->name('accounting.corporate-tax.export');
    Route::post('accounting/corporate-tax', [CorporateTaxReturnController::class, 'store'])->name('accounting.corporate-tax.store');
    Route::post('accounting/corporate-tax/{taxReturn}/approve', [CorporateTaxReturnController::class, 'approve'])->name('accounting.corporate-tax.approve');
    Route::post('accounting/corporate-tax/{taxReturn}/file', [CorporateTaxReturnController::class, 'file'])->name('accounting.corporate-tax.file');
    Route::post('accounting/corporate-tax/{taxReturn}/pay', [CorporateTaxReturnController::class, 'pay'])->name('accounting.corporate-tax.pay');
    Route::post('accounting/corporate-tax/{taxReturn}/reverse-payment', [CorporateTaxReturnController::class, 'reversePayment'])->name('accounting.corporate-tax.payment.reverse');
    Route::post('accounting/corporate-tax/{taxReturn}/reverse-provision', [CorporateTaxReturnController::class, 'reverseProvision'])->name('accounting.corporate-tax.provision.reverse');
    Route::get('accounting/vat-return', [VatReturnController::class, 'index'])->name('accounting.vat-return');
    Route::get('accounting/vat-return.csv', [VatReturnController::class, 'export'])->name('accounting.vat-return.export');
    Route::post('accounting/vat-return/prepare', [VatReturnController::class, 'prepare'])->name('accounting.vat-return.prepare');
    Route::post('accounting/vat-returns/{vatReturn}/file', [VatReturnController::class, 'file'])->name('accounting.vat-return.file');
    Route::post('accounting/vat-returns/{vatReturn}/adjustments', [VatReturnController::class, 'adjust'])->name('accounting.vat-return.adjustments.store');
    Route::post('accounting/vat-returns/{vatReturn}/settle', [VatReturnController::class, 'settle'])->name('accounting.vat-return.settle');
    Route::post('accounting/vat-settlements/{settlement}/receive-refund', [VatReturnController::class, 'receiveRefund'])->name('accounting.vat-return.refund.receive');
    Route::post('accounting/vat-settlements/{settlement}/reverse', [VatReturnController::class, 'reverseSettlement'])->name('accounting.vat-return.settlement.reverse');
    Route::post('accounting/vat-settlements/{settlement}/reverse-refund', [VatReturnController::class, 'reverseRefund'])->name('accounting.vat-return.refund.reverse');
    Route::get('accounting/trial-balance.csv', [AccountingController::class, 'exportTrialBalance'])->name('accounting.trial-balance.export');
    Route::get('accounting/overview.csv', [AccountingController::class, 'exportOverview'])->name('accounting.overview.export');
    Route::get('bank-reconciliation', [BankReconciliationController::class, 'index'])->name('bank-reconciliation.index');
    Route::post('bank-reconciliation/accounts', [BankReconciliationController::class, 'storeAccount'])->name('bank-reconciliation.accounts.store');
    Route::put('bank-reconciliation/accounts/{bankAccount}/ledger-account', [BankReconciliationController::class, 'linkLedgerAccount'])->name('bank-reconciliation.accounts.ledger-account');
    Route::post('bank-reconciliation/import', [BankReconciliationController::class, 'import'])->name('bank-reconciliation.import');
    Route::post('bank-reconciliation/lines/{statementLine}/match', [BankReconciliationController::class, 'match'])->name('bank-reconciliation.lines.match');
    Route::post('bank-reconciliation/lines/{statementLine}/unmatch', [BankReconciliationController::class, 'unmatch'])->name('bank-reconciliation.lines.unmatch');
    Route::post('bank-reconciliation/lines/{statementLine}/settle', [BankReconciliationController::class, 'settle'])->name('bank-reconciliation.lines.settle');
    Route::post('bank-reconciliation/lines/{statementLine}/reverse-settlement', [BankReconciliationController::class, 'reverseSettlement'])->name('bank-reconciliation.lines.reverse-settlement');
    Route::post('accounting/accounts', [AccountingController::class, 'storeAccount'])->name('accounting.accounts.store');
    Route::put('accounting/accounts/{account}', [AccountingController::class, 'updateAccount'])->name('accounting.accounts.update');
    Route::post('accounting/periods', [AccountingController::class, 'storePeriod'])->name('accounting.periods.store');
    Route::post('accounting/periods/{period}/close', [AccountingController::class, 'closePeriod'])->name('accounting.periods.close');
    Route::post('accounting/periods/{period}/reopen', [AccountingController::class, 'reopenPeriod'])->name('accounting.periods.reopen');
    Route::get('accounting/periods/{period}/close-readiness', PeriodCloseReadinessController::class)->name('accounting.periods.close-readiness');
    Route::get('accounting/periods/{period}/close-readiness.csv', [PeriodCloseReadinessController::class, 'export'])->name('accounting.periods.close-readiness.export');
    Route::post('accounting/journals', [AccountingController::class, 'postJournal'])->name('accounting.journals.store');
    Route::post('accounting/opening-balances', [AccountingController::class, 'postOpeningBalance'])->name('accounting.opening-balances.store');
    Route::post('accounting/journals/{entry}/reverse', [AccountingController::class, 'reverseJournal'])->name('accounting.journals.reverse');
    Route::get('procurement', [ProcurementController::class, 'index'])->name('procurement.index');
    Route::post('procurement/requests', [ProcurementController::class, 'storeRequest'])->name('procurement.requests.store');
    Route::post('procurement/requests/{purchaseRequest}/submit', [ProcurementController::class, 'submit'])->name('procurement.requests.submit');
    Route::post('procurement/requests/{purchaseRequest}/approve', [ProcurementController::class, 'approve'])->name('procurement.requests.approve');
    Route::post('procurement/requests/{purchaseRequest}/rfqs', [ProcurementController::class, 'storeRfq'])->name('procurement.rfqs.store');
    Route::post('procurement/rfqs/{rfq}/quotation', [ProcurementController::class, 'storeQuotation'])->name('procurement.quotations.store');
    Route::post('procurement/quotations/{quotation}/order', [ProcurementController::class, 'issueOrder'])->name('procurement.orders.store');
    Route::post('procurement/orders/{purchaseOrder}/receive', [ProcurementController::class, 'receive'])->name('procurement.orders.receive');
    Route::post('procurement/orders/{purchaseOrder}/bill', [ProcurementController::class, 'convertToBill'])->name('procurement.orders.bill');
    Route::post('vendor-bills', [VendorBillController::class, 'store'])->name('vendor-bills.store');
    Route::put('vendor-bills/{bill}/accounting-treatment', [VendorBillController::class, 'updateTreatment'])->name('vendor-bills.treatment.update');
    Route::post('vendor-bills/{bill}/post', [VendorBillController::class, 'post'])->name('vendor-bills.post');
    Route::post('vendor-bills/{bill}/payments', [VendorBillController::class, 'pay'])->name('vendor-bills.pay');
    Route::post('vendor-bills/{bill}/credit-notes', [VendorCreditNoteController::class, 'store'])->name('vendor-credit-notes.store');
    Route::post('vendor-credit-notes/{creditNote}/approve', [VendorCreditNoteController::class, 'approve'])->name('vendor-credit-notes.approve');
    Route::post('vendor-credit-notes/{creditNote}/reject', [VendorCreditNoteController::class, 'reject'])->name('vendor-credit-notes.reject');
    Route::post('vendor-credit-notes/{creditNote}/reverse', [VendorCreditNoteController::class, 'reverse'])->name('vendor-credit-notes.reverse');
    Route::get('reports/property-profitability', PropertyProfitabilityController::class)->name('reports.property-profitability');
    Route::get('reports/owner-statements', [OwnerStatementController::class, 'index'])->name('reports.owner-statements.index');
    Route::get('reports/owner-statements.csv', [OwnerStatementController::class, 'export'])->name('reports.owner-statements.export');
    Route::get('operations', [OperationsOverviewController::class, 'index'])->name('operations.overview');
    Route::get('operations/fleet', [FleetController::class, 'index'])->name('fleet.index');
    Route::post('operations/fleet', [FleetController::class, 'store'])->name('fleet.store');
    Route::get('operations/fleet/{vehicle}', [FleetController::class, 'show'])->name('fleet.show');
    Route::post('operations/fleet/{vehicle}/assignments', [FleetController::class, 'assign'])->name('fleet.assign');
    Route::post('operations/fleet/{vehicle}/services', [FleetController::class, 'service'])->name('fleet.service');
    Route::post('operations/fleet/{vehicle}/status', [FleetController::class, 'status'])->name('fleet.status');
    Route::post('operations/fleet-assignments/{assignment}/return', [FleetController::class, 'returnVehicle'])->name('fleet.return');
    Route::post('operations/fleet-services/{service}/complete', [FleetController::class, 'complete'])->name('fleet.complete');
    Route::post('operations/fleet-services/{service}/cancel', [FleetController::class, 'cancel'])->name('fleet.cancel');
    Route::get('operations/projects', [ConstructionController::class, 'index'])->name('construction.index');
    Route::post('operations/projects', [ConstructionController::class, 'store'])->name('construction.store');
    Route::get('operations/projects/{project}', [ConstructionController::class, 'show'])->name('construction.show');
    Route::post('operations/projects/{project}/boq', [ConstructionController::class, 'item'])->name('construction.boq');
    Route::post('operations/projects/{project}/status', [ConstructionController::class, 'status'])->name('construction.status');
    Route::post('operations/projects/{project}/claims', [ConstructionController::class, 'claim'])->name('construction.claims');
    Route::post('operations/boq/{item}/progress', [ConstructionController::class, 'progress'])->name('construction.progress');
    Route::post('operations/boq-progress/{progress}/void', [ConstructionController::class, 'voidProgress'])->name('construction.progress.void');
    Route::post('operations/contractor-claims/{claim}/approve', [ConstructionController::class, 'approve'])->name('construction.claims.approve');
    Route::post('operations/contractor-claims/{claim}/reject', [ConstructionController::class, 'reject'])->name('construction.claims.reject');
    Route::post('operations/contractor-claims/{claim}/bill', [ConstructionController::class, 'bill'])->name('construction.claims.bill');
    Route::get('operations/amc', [AmcController::class, 'index'])->name('amc.index');
    Route::post('operations/amc', [AmcController::class, 'store'])->name('amc.store');
    Route::post('operations/amc/equipment', [AmcController::class, 'equipment'])->name('amc.equipment');
    Route::post('operations/amc/{contract}/visits', [AmcController::class, 'visit'])->name('amc.visits');
    Route::post('operations/amc/{contract}/cancel', [AmcController::class, 'cancel'])->name('amc.cancel');
    Route::post('operations/reports/filters', [OperationsReportController::class, 'saveFilter'])->name('operations.reports.filters.save');
    Route::delete('operations/reports/filters/{filter}', [OperationsReportController::class, 'removeFilter'])->name('operations.reports.filters.remove');
    Route::get('operations/reports', [OperationsReportController::class, 'index'])->name('operations.reports');
    Route::get('operations/reports.csv', [OperationsReportController::class, 'export'])->name('operations.reports.export');
    Route::get('operations/overview.csv', [OperationsOverviewController::class, 'export'])->name('operations.overview.export');
    Route::get('operations/helpdesk', [JobSlaController::class, 'index'])->name('helpdesk.index');
    Route::post('maintenance/{maintenanceRequest}/sla', [JobSlaController::class, 'enable'])->name('maintenance.sla.enable');
    Route::post('maintenance/{maintenanceRequest}/sla/acknowledge', [JobSlaController::class, 'acknowledge'])->name('maintenance.sla.acknowledge');
    Route::get('maintenance', [MaintenanceRequestController::class, 'index'])->name('maintenance.index');
    Route::post('maintenance', [MaintenanceRequestController::class, 'store'])->name('maintenance.store');
    Route::post('maintenance/vendors', [MaintenanceRequestController::class, 'storeVendor'])->name('maintenance.vendors.store');
    Route::put('maintenance/{maintenanceRequest}/status', [MaintenanceRequestController::class, 'updateStatus'])->name('maintenance.status.update');
    Route::put('maintenance/{maintenanceRequest}/work-order', [MaintenanceRequestController::class, 'updateWorkOrder'])->name('maintenance.work-order.update');
    Route::post('operations/spare-parts/receipts/{movement}/cost', [SparePartsController::class, 'receiptCost'])->name('stock.receipt-cost');
    Route::get('operations/spare-parts', [SparePartsController::class, 'index'])->name('stock.index');
    Route::post('operations/spare-parts/parts', [SparePartsController::class, 'part'])->name('stock.parts');
    Route::post('operations/spare-parts/stores', [SparePartsController::class, 'store'])->name('stock.stores');
    Route::post('operations/spare-parts/movements', [SparePartsController::class, 'movement'])->name('stock.movements');
    Route::post('operations/spare-parts/transfers', [SparePartsController::class, 'transfer'])->name('stock.transfers');
    Route::post('operations/spare-parts/transfers/{movement}/reverse', [SparePartsController::class, 'reverseTransfer'])->name('stock.transfers.reverse');
    Route::get('maintenance/{maintenanceRequest}/job-card', [MaintenanceJobCardController::class, 'show'])->name('maintenance.job-card');
    Route::post('maintenance/{maintenanceRequest}/job-card/finish', [MaintenanceJobCardController::class, 'finish'])->name('maintenance.job-card.finish');
    Route::post('maintenance/{maintenanceRequest}/job-card/confirm', [MaintenanceJobCardController::class, 'confirm'])->name('maintenance.job-card.confirm');
    Route::post('maintenance/{maintenanceRequest}/job-card/reopen', [MaintenanceJobCardController::class, 'reopen'])->name('maintenance.job-card.reopen');
    Route::post('maintenance/{maintenanceRequest}/job-card/notes', [MaintenanceJobCardController::class, 'note'])->name('maintenance.job-card.notes');
    Route::post('maintenance/{maintenanceRequest}/job-card/tasks', [MaintenanceJobCardController::class, 'task'])->name('maintenance.job-card.tasks');
    Route::put('maintenance/{maintenanceRequest}/job-card/tasks/{task}', [MaintenanceJobCardController::class, 'checkTask'])->name('maintenance.job-card.tasks.check');
    Route::post('maintenance/{maintenanceRequest}/job-card/costs', [MaintenanceJobCardController::class, 'cost'])->name('maintenance.job-card.costs');
    Route::post('maintenance/{maintenanceRequest}/job-card/costs/{line}/void', [MaintenanceJobCardController::class, 'voidCost'])->name('maintenance.job-card.costs.void');
    Route::post('maintenance/{maintenanceRequest}/job-card/evidence', [MaintenanceJobCardController::class, 'evidence'])->name('maintenance.job-card.evidence');
    Route::get('maintenance/{maintenanceRequest}/job-card/evidence/{document}', [MaintenanceJobCardController::class, 'download'])->name('maintenance.job-card.evidence.download');
    Route::get('preventive-maintenance', [PreventiveMaintenanceController::class, 'index'])->name('preventive-maintenance.index');
    Route::post('preventive-maintenance', [PreventiveMaintenanceController::class, 'store'])->name('preventive-maintenance.store');
    Route::put('preventive-maintenance/{plan}/automation', [PreventiveMaintenanceController::class, 'automation'])->name('preventive-maintenance.automation');
    Route::post('preventive-maintenance/{plan}/generate', [PreventiveMaintenanceController::class, 'generate'])->name('preventive-maintenance.generate');
    Route::get('compliance-documents', [ComplianceDocumentController::class, 'index'])->name('compliance-documents.index');
    Route::post('compliance-documents', [ComplianceDocumentController::class, 'store'])->name('compliance-documents.store');
    Route::get('compliance-documents/{document}/download', [ComplianceDocumentController::class, 'download'])->name('compliance-documents.download');
    Route::get('reports/{report}.csv', OperationsExportController::class)->name('reports.export');
    Route::get('inventory', [InventoryController::class, 'index'])->name('inventory.index');
    Route::get('inventory/properties/{property}', [InventoryController::class, 'showProperty'])->name('inventory.properties.show');
    Route::get('inventory/buildings/{building}/skyline', [InventoryController::class, 'skyline'])->name('inventory.buildings.skyline');
    Route::get('inventory/units/{unit}', [InventoryController::class, 'showUnit'])->name('inventory.units.show');
    Route::post('inventory/properties', [InventoryController::class, 'storeProperty'])->name('inventory.properties.store');
    Route::put('inventory/properties/{property}/owners', [InventoryController::class, 'assignOwner'])->name('inventory.properties.owners.assign');
    Route::post('inventory/buildings', [InventoryController::class, 'storeBuilding'])->name('inventory.buildings.store');
    Route::post('inventory/units', [InventoryController::class, 'storeUnit'])->name('inventory.units.store');
    Route::put('inventory/units/{unit}/status', [InventoryController::class, 'updateUnitStatus'])->name('inventory.units.status.update');
    Route::put('inventory/units/{unit}/floor', [InventoryController::class, 'updateUnitFloor'])->name('inventory.units.floor.update');
    Route::post('inventory/leases/{lease}/rent-invoices', [RentInvoiceLinkController::class, 'store'])->name('inventory.rent-invoices.store');
    Route::delete('inventory/leases/{lease}/rent-invoices/{invoice}', [RentInvoiceLinkController::class, 'destroy'])->name('inventory.rent-invoices.destroy');
    Route::get('documents/{document}/versions', [DocumentVersionController::class, 'show'])->name('documents.versions');
    Route::post('documents/{document}/versions', [DocumentVersionController::class, 'store'])->name('documents.versions.store');
    Route::post('documents/{document}/archive', [DocumentVersionController::class, 'archive'])->name('documents.archive');
    Route::post('documents/{document}/restore', [DocumentVersionController::class, 'restore'])->name('documents.restore');
    Route::get('documents/{document}/preview', [DocumentVersionController::class, 'preview'])->name('documents.preview');
    Route::post('inventory/properties/{property}/documents', [DocumentController::class, 'storeProperty'])->name('inventory.properties.documents.store');
    Route::post('inventory/units/{unit}/documents', [DocumentController::class, 'storeUnit'])->name('inventory.units.documents.store');
    Route::get('documents/{document}/download', [DocumentController::class, 'download'])->name('documents.download');
    Route::put('crm/pipelines/{pipeline}/stages/{stage}/rules', [CrmPipelineController::class, 'saveRules'])->name('crm.pipeline-stages.rules');
    Route::put('crm/pipelines/{pipeline}/stages/{stage}/assignee-notification', [CrmPipelineController::class, 'saveAssigneeNotification'])->name('crm.pipeline-stages.assignee-notification');
    Route::put('crm/pipelines/{pipeline}/stages/{stage}/follow-up-rule', [CrmPipelineController::class, 'saveFollowUpRule'])->name('crm.pipeline-stages.follow-up-rule');
    Route::put('crm/pipelines/{pipeline}/stages/{stage}/assignment-rule', [CrmPipelineController::class, 'saveAssignmentRule'])->name('crm.pipeline-stages.assignment-rule');
    Route::put('crm/leads/{lead}/details', [CrmLeadController::class, 'updateDetails'])->name('crm.leads.details');
    Route::get('crm/pipeline-report', CrmPipelineReportController::class)->name('crm.pipeline-report');
    Route::get('crm/hierarchy', [CrmHierarchyController::class, 'index'])->name('crm.hierarchy.index');
    Route::put('crm/hierarchy/placement', [CrmHierarchyController::class, 'place'])->name('crm.hierarchy.place');
    Route::post('crm/hierarchy/grants', [CrmHierarchyController::class, 'grant'])->name('crm.hierarchy.grant');
    Route::delete('crm/hierarchy/grants/{grant}', [CrmHierarchyController::class, 'revoke'])->name('crm.hierarchy.revoke');
    Route::put('crm/hierarchy/edit-grant', [CrmHierarchyController::class, 'setEditGrant'])->name('crm.hierarchy.edit-grant');
    Route::put('crm/hierarchy/{kind}/{id}/active', [CrmHierarchyController::class, 'setActive'])->name('crm.hierarchy.active');
    Route::post('crm/hierarchy/{kind}', [CrmHierarchyController::class, 'create'])->name('crm.hierarchy.create');
    Route::get('crm/pipelines', [CrmPipelineController::class, 'index'])->name('crm.pipelines.index');
    Route::get('crm/automation', [CrmAutomationController::class, 'index'])->name('crm.automation.index');
    Route::post('crm/automation', [CrmAutomationController::class, 'store'])->name('crm.automation.store');
    Route::put('crm/automation/{rule}', [CrmAutomationController::class, 'update'])->name('crm.automation.update');
    Route::delete('crm/automation/{rule}', [CrmAutomationController::class, 'destroy'])->name('crm.automation.disable');
    Route::post('crm/pipelines', [CrmPipelineController::class, 'savePipeline'])->name('crm.pipelines.store');
    Route::put('crm/pipelines/{pipeline}', [CrmPipelineController::class, 'savePipeline'])->name('crm.pipelines.update');
    Route::post('crm/pipelines/{pipeline}/stages', [CrmPipelineController::class, 'saveStage'])->name('crm.pipeline-stages.store');
    Route::put('crm/pipelines/{pipeline}/stages/{stage}', [CrmPipelineController::class, 'saveStage'])->name('crm.pipeline-stages.update');
    Route::post('crm/pipelines/{pipeline}/reasons', [CrmPipelineController::class, 'saveReason'])->name('crm.lost-reasons.store');
    Route::put('crm/pipelines/{pipeline}/reasons/{reason}', [CrmPipelineController::class, 'saveReason'])->name('crm.lost-reasons.update');
    Route::delete('crm/configuration/{kind}/{id}', [CrmPipelineController::class, 'destroy'])->name('crm.configuration.destroy');
    Route::put('crm/leads/{lead}/stage', [CrmLeadController::class, 'move'])->name('crm.leads.stage');
    Route::post('crm/leads/{lead}/transfer', [CrmLeadController::class, 'transfer'])->name('crm.leads.transfer');
    Route::get('crm/settings/fields', [CrmSettingsDataController::class, 'fields'])->name('crm.settings.fields');
    Route::post('crm/settings/fields', [CrmSettingsDataController::class, 'saveField'])->name('crm.settings.fields.store');
    Route::put('crm/settings/fields/{field}', [CrmSettingsDataController::class, 'saveField'])->name('crm.settings.fields.update');
    Route::get('crm/records/{entity}/{record}/fields', [CrmSettingsDataController::class, 'recordFields'])->name('crm.records.fields');
    Route::put('crm/records/{entity}/{record}/fields', [CrmSettingsDataController::class, 'updateRecordFields'])->name('crm.records.fields.update');
    Route::match(['put', 'post'], 'crm/deals/{deal}/financial-links', [CrmDealController::class, 'financialLink'])->name('crm.deals.financial-links');
    Route::get('reference-workflows', [ReferenceWorkflowController::class, 'index'])->name('reference-workflows.index');
    Route::post('reference-workflows', [ReferenceWorkflowController::class, 'save'])->name('reference-workflows.store');
    Route::get('reference-workflows/{record}', [ReferenceWorkflowController::class, 'show'])->whereNumber('record')->name('reference-workflows.show');
    Route::put('reference-workflows/{record}', [ReferenceWorkflowController::class, 'save'])->whereNumber('record')->name('reference-workflows.update');
    Route::put('reference-workflows/{record}/stage', [ReferenceWorkflowController::class, 'move'])->name('reference-workflows.stage');
    Route::post('reference-workflows/{record}/invoice', [ReferenceWorkflowController::class, 'invoice'])->name('reference-workflows.invoice');
    Route::post('reference-workflows/pipelines', [ReferenceWorkflowController::class, 'pipeline'])->name('reference-workflows.pipelines.store');
    Route::put('reference-workflows/pipelines/{pipeline}', [ReferenceWorkflowController::class, 'pipeline'])->name('reference-workflows.pipelines.update');
    Route::post('reference-workflows/pipelines/{pipeline}/stages', [ReferenceWorkflowController::class, 'stage'])->name('reference-workflows.stages.store');
    Route::put('reference-workflows/pipelines/{pipeline}/stages/{stage}', [ReferenceWorkflowController::class, 'stage'])->name('reference-workflows.stages.update');
    Route::post('organization/reference-settings/currencies/rebase', [ReferenceConfigurationController::class, 'rebase'])->name('reference-settings.currencies.rebase');
    Route::post('organization/provider-packets', [ReferenceConfigurationController::class, 'packet'])->name('reference-settings.provider-packets');
    Route::get('organization/reference-settings/{kind}', [ReferenceConfigurationController::class, 'index'])->name('reference-settings.index');
    Route::get('organization/crm-catalog/{kind}', [CrmCatalogController::class, 'index'])->name('crm-catalog.index');
    Route::post('organization/crm-catalog/{kind}', [CrmCatalogController::class, 'save'])->name('crm-catalog.store');
    Route::put('organization/crm-catalog/{kind}/{record}', [CrmCatalogController::class, 'save'])->name('crm-catalog.update');
    Route::get('crm/leads/{lead}/products', [CrmCatalogController::class, 'leadProducts'])->name('crm.leads.products');
    Route::get('crm/leads/{lead}/requirements', [CrmLeadRequirementController::class, 'show'])->name('crm.leads.requirements.show');
    Route::put('crm/leads/{lead}/requirements', [CrmLeadRequirementController::class, 'update'])->name('crm.leads.requirements.update');
    Route::get('crm/settings/lead-requirements', [CrmLeadRequirementController::class, 'configuration'])->name('crm.settings.lead-requirements.show');
    Route::put('crm/settings/lead-requirements', [CrmLeadRequirementController::class, 'updateConfiguration'])->name('crm.settings.lead-requirements.update');
    Route::post('crm/leads/{lead}/products', [CrmCatalogController::class, 'saveLeadProduct'])->name('crm.leads.products.store');
    Route::put('crm/leads/{lead}/products/{line}', [CrmCatalogController::class, 'saveLeadProduct'])->name('crm.leads.products.update');
    Route::delete('crm/leads/{lead}/products/{line}', [CrmCatalogController::class, 'removeLeadProduct'])->name('crm.leads.products.destroy');
    Route::post('organization/reference-settings/{kind}', [ReferenceConfigurationController::class, 'save'])->name('reference-settings.store');
    Route::put('organization/reference-settings/{kind}/{record}', [ReferenceConfigurationController::class, 'save'])->name('reference-settings.update');
    Route::get('crm/settings/calendar', [CrmSettingsDataController::class, 'calendar'])->name('crm.settings.calendar');
    Route::put('crm/settings/calendar', [CrmSettingsDataController::class, 'saveCalendar'])->name('crm.settings.calendar.update');
    Route::get('crm/settings/data', [CrmSettingsDataController::class, 'index'])->name('crm.settings.data');
    Route::post('crm/settings/options', [CrmSettingsDataController::class, 'option'])->name('crm.settings.options.store');
    Route::put('crm/settings/options/{option}', [CrmSettingsDataController::class, 'option'])->name('crm.settings.options.update');
    Route::put('crm/settings/section-access', [CrmSettingsDataController::class, 'section'])->name('crm.settings.section-access');
    Route::get('crm/deals', [CrmDealController::class, 'index'])->name('crm.deals.index');
    Route::get('crm/deals/export', [CrmDealController::class, 'export'])->name('crm.deals.export');
    Route::post('crm/deals/{deal}/activities', [CrmDealController::class, 'activity'])->name('crm.deals.activities.store');
    Route::put('crm/deals/{deal}/activities/{activity}', [CrmDealController::class, 'activity'])->name('crm.deals.activities.update');
    Route::get('crm/deals/automation', [CrmDealController::class, 'automation'])->name('crm.deals.automation');
    Route::post('crm/deals/automation', [CrmDealController::class, 'saveAutomation'])->name('crm.deals.automation.store');
    Route::put('crm/deals/automation/{rule}', [CrmDealController::class, 'saveAutomation'])->name('crm.deals.automation.update');
    Route::get('crm/deals/configuration', [CrmDealController::class, 'configuration'])->name('crm.deals.configuration');
    Route::post('crm/deals/pipelines', [CrmDealController::class, 'pipeline'])->name('crm.deal-pipelines.store');
    Route::put('crm/deals/pipelines/{pipeline}', [CrmDealController::class, 'pipeline'])->name('crm.deal-pipelines.update');
    Route::post('crm/deals/pipelines/{pipeline}/stages', [CrmDealController::class, 'stage'])->name('crm.deal-stages.store');
    Route::put('crm/deals/pipelines/{pipeline}/stages/{stage}', [CrmDealController::class, 'stage'])->name('crm.deal-stages.update');
    Route::put('crm/deals/pipelines/{pipeline}/access', [CrmDealController::class, 'access'])->name('crm.deal-pipelines.access');
    Route::delete('crm/deals/configuration/{kind}/{id}', [CrmDealController::class, 'destroy'])->name('crm.deals.configuration.destroy');
    Route::post('crm/deals', [CrmDealController::class, 'store'])->name('crm.deals.store');
    Route::post('crm/leads/{lead}/deal', [CrmDealController::class, 'fromLead'])->name('crm.leads.deal');
    Route::get('crm/deals/{deal}', [CrmDealController::class, 'show'])->name('crm.deals.show');
    Route::put('crm/deals/{deal}', [CrmDealController::class, 'update'])->name('crm.deals.update');
    Route::put('crm/deals/{deal}/stage', [CrmDealController::class, 'move'])->name('crm.deals.stage');
    Route::match(['post', 'put'], 'crm/deals/{deal}/transfer', [CrmDealController::class, 'transfer'])->name('crm.deals.transfer');
    Route::get('crm/leads', [CrmLeadController::class, 'index'])->name('crm.leads.index');
    Route::get('deals', [CrmPageController::class, 'deals'])->name('deals.index');
    Route::get('deals/{deal}', [CrmPageController::class, 'deal'])->whereNumber('deal')->name('deals.show');
    Route::get('crm/permissions', [CrmPageController::class, 'permissions'])->name('crm.permissions');
    Route::get('crm/deal-pipelines', [CrmPageController::class, 'dealPipelines'])->name('crm.deal-pipelines.page');
    Route::get('crm/deal-automation', [CrmPageController::class, 'dealAutomation'])->name('crm.deal-automation.page');
    Route::get('crm/settings/working-calendar', [CrmPageController::class, 'workingCalendar'])->name('crm.settings.calendar.page');
    Route::get('crm/settings', [CrmPageController::class, 'settings'])->name('crm.settings');
    Route::get('crm/settings/reference/{section}', [CrmPageController::class, 'referenceSettings'])->name('crm.settings.reference');
    Route::get('crm/settings/lists', [CrmPageController::class, 'selectionLists'])->name('crm.settings.lists');
    Route::get('crm/settings/requirement-options', [CrmPageController::class, 'requirementOptions'])->name('crm.settings.requirement-options');
    Route::get('crm/settings/payment-systems', [CrmPageController::class, 'providers'])->name('crm.settings.providers');
    Route::get('crm/settings/catalog/{section}', [CrmPageController::class, 'catalogSettings'])->name('crm.settings.catalog');
    Route::get('companies', [CrmPageController::class, 'companies'])->name('companies.index');
    Route::get('contacts/{contact}', [CrmPageController::class, 'contact'])->whereNumber('contact')->name('contacts.show');
    Route::get('companies/{company}', [CrmPageController::class, 'company'])->whereNumber('company')->name('companies.show');
    Route::get('workflows', [CrmPageController::class, 'workflows'])->name('workflows.index');
    Route::get('workflows/pipelines', [CrmPageController::class, 'workflowPipelines'])->name('workflows.pipelines');
    Route::get('crm/leads/preferences', [CrmLeadPreferenceController::class, 'index'])->name('crm.leads.preferences.index');
    Route::post('crm/leads/preferences', [CrmLeadPreferenceController::class, 'store'])->name('crm.leads.preferences.store');
    Route::delete('crm/leads/preferences/{preset}', [CrmLeadPreferenceController::class, 'destroy'])->name('crm.leads.preferences.destroy');
    Route::get('crm/leads/import/sample', [CrmLeadImportController::class, 'sample'])->name('crm.leads.import.sample');
    Route::get('crm/leads/import', [CrmLeadImportController::class, 'index'])->name('crm.leads.import.index');
    Route::get('crm/leads/export', [CrmLeadExportController::class, 'index'])->name('crm.leads.export.index');
    Route::get('crm/leads/export/download', [CrmLeadExportController::class, 'download'])->name('crm.leads.export.download');
    Route::get('crm/leads/export/activities', [CrmLeadExportController::class, 'activities'])->name('crm.leads.export.activities');
    Route::put('crm/leads/export/grants', [CrmLeadExportController::class, 'grant'])->name('crm.leads.export.grants');
    Route::post('crm/leads/import/preview', [CrmLeadImportController::class, 'preview'])->name('crm.leads.import.preview');
    Route::post('crm/leads/import/{batch}/commit', [CrmLeadImportController::class, 'commit'])->name('crm.leads.import.commit');
    Route::get('crm/leads/qualified', QualifiedLeadController::class)->name('crm.leads.qualified');
    Route::get('crm/leads/{lead}', [CrmLeadController::class, 'show'])->name('crm.leads.show');
    Route::get('crm/custom-fields', [CrmCustomFieldController::class, 'index'])->name('crm.custom-fields.index');
    Route::post('crm/custom-fields', [CrmCustomFieldController::class, 'store'])->name('crm.custom-fields.store');
    Route::put('crm/custom-fields/{field}', [CrmCustomFieldController::class, 'update'])->name('crm.custom-fields.update');
    Route::delete('crm/custom-fields/{field}', [CrmCustomFieldController::class, 'destroy'])->name('crm.custom-fields.archive');
    Route::post('crm/leads', [CrmLeadController::class, 'store'])->name('crm.leads.store');
    Route::post('crm/leads/{lead}/convert', [CrmLeadController::class, 'convert'])->name('crm.leads.convert');
    Route::put('crm/leads/{lead}/assignment', [CrmLeadController::class, 'assign'])->name('crm.leads.assignment');
    Route::get('crm/contacts', [CrmContactController::class, 'index'])->name('crm.contacts.index');
    Route::post('crm/contacts', [CrmContactController::class, 'store'])->name('crm.contacts.store');
    Route::get('crm/contacts/{contact}', [CrmContactController::class, 'show'])->name('crm.contacts.show');
    Route::put('crm/contacts/{contact}', [CrmContactController::class, 'update'])->name('crm.contacts.update');
    Route::get('crm/companies', [CrmCompanyController::class, 'index'])->name('crm.companies.index');
    Route::post('crm/companies', [CrmCompanyController::class, 'store'])->name('crm.companies.store');
    Route::get('crm/companies/{company}', [CrmCompanyController::class, 'show'])->name('crm.companies.show');
    Route::put('crm/companies/{company}', [CrmCompanyController::class, 'update'])->name('crm.companies.update');
    Route::get('crm/activities', [CrmActivityController::class, 'index'])->name('crm.activities.index');
    Route::post('crm/activities', [CrmActivityController::class, 'store'])->name('crm.activities.store');
    Route::put('crm/activities/{activity}', [CrmActivityController::class, 'update'])->name('crm.activities.update');
    Route::post('crm/activities/{activity}/complete', [CrmActivityController::class, 'complete'])->name('crm.activities.complete');
    Route::get('real-estate/people', [RealEstatePartyController::class, 'index'])->name('real-estate.people.index');
    Route::post('real-estate/people/{type}', [RealEstatePartyController::class, 'store'])->name('real-estate.people.store');
    Route::put('real-estate/people/brokers/{broker}/user', [RealEstatePartyController::class, 'mapBrokerUser'])->name('real-estate.people.brokers.user');
    Route::get('real-estate/listings', [ListingController::class, 'index'])->name('real-estate.listings.index');
    Route::get('real-estate/secondary-market', [ListingController::class, 'secondaryMarket'])->name('real-estate.secondary-market.index');
    Route::post('real-estate/listings', [ListingController::class, 'store'])->name('real-estate.listings.store');
    Route::put('real-estate/listings/{listing}/status', [ListingController::class, 'updateStatus'])->name('real-estate.listings.status.update');
    Route::post('real-estate/listings/inquiries', [ListingController::class, 'storeInquiry'])->name('real-estate.listings.inquiries.store');
    Route::get('real-estate/brokerage', [BrokerageController::class, 'index'])->name('real-estate.brokerage.index');
    Route::post('real-estate/brokerage/commission-plans', [BrokerageController::class, 'storePlan'])->name('real-estate.brokerage.plans.store');
    Route::post('real-estate/brokerage/commissions/{commission}/allocation', [BrokerageController::class, 'submitAllocation'])->name('real-estate.brokerage.allocations.submit');
    Route::post('real-estate/brokerage/allocations/{allocation}/approve', [BrokerageController::class, 'approveAllocation'])->name('real-estate.brokerage.allocations.approve');
    Route::post('real-estate/brokerage/allocations/{allocation}/reject', [BrokerageController::class, 'rejectAllocation'])->name('real-estate.brokerage.allocations.reject');
    Route::get('organization', [OrganizationController::class, 'edit'])->name('organization.edit');
    Route::put('organization/switch/{organization}', [OrganizationController::class, 'switch'])->name('organization.switch');
    Route::put('organization/tax-settings', [OrganizationController::class, 'updateTaxSettings'])->name('organization.tax-settings.update');
    Route::post('organization/invitations', [OrganizationController::class, 'invite'])->name('organization.invitations.store');
    Route::post('organization/invitations/{invitation}/accept', [OrganizationController::class, 'accept'])->name('organization.invitations.accept');
    Route::put('organization/members/{member}', [OrganizationController::class, 'updateMember'])->name('organization.members.update');
    Route::delete('organization/members/{member}', [OrganizationController::class, 'removeMember'])->name('organization.members.destroy');
});

Route::middleware(['auth', 'verified'])->group(function (): void {
    Route::get('organization/api-tokens', [ReadTokenController::class, 'index'])->name('api-tokens.index');
    Route::post('organization/api-tokens', [ReadTokenController::class, 'store'])->middleware('throttle:20,1')->name('api-tokens.store');
    Route::delete('organization/api-tokens/{token}', [ReadTokenController::class, 'revoke'])->name('api-tokens.revoke');
});

Route::middleware(['auth', 'verified'])->group(function (): void {
    Route::get('operations/scheduled-reports', [PrivateReportsController::class, 'index'])->name('private-reports.index');
    Route::post('operations/scheduled-reports', [PrivateReportsController::class, 'store'])->name('private-reports.store');
    Route::put('operations/scheduled-reports/{schedule}', [PrivateReportsController::class, 'toggle'])->name('private-reports.toggle');
    Route::get('operations/scheduled-reports/deliveries/{delivery}', [PrivateReportsController::class, 'download'])->name('private-reports.download');
});

Route::middleware(['auth', 'verified'])->group(function (): void {
    Route::get('inventory/imports', [InventoryImportController::class, 'index'])->name('inventory.imports');
    Route::post('inventory/imports', [InventoryImportController::class, 'preview'])->name('inventory.imports.preview');
    Route::post('inventory/imports/{batch}/commit', [InventoryImportController::class, 'commit'])->name('inventory.imports.commit');
});

Route::post('locale', LocaleController::class)->middleware('throttle:30,1')->name('locale.update');

Route::middleware(['auth', 'verified'])->group(function (): void {
    Route::get('documents/signatures', [SignatureRequestController::class, 'index'])->name('signatures.index');
    Route::post('documents/signatures', [SignatureRequestController::class, 'store'])->name('signatures.store');
    Route::post('documents/signatures/{signature}/cancel', [SignatureRequestController::class, 'cancel'])->name('signatures.cancel');
    Route::get('documents/signatures/{signature}/packet', [SignatureRequestController::class, 'packet'])->name('signatures.packet');
});

require __DIR__.'/settings.php';
