import {
    ArrowLeftRight,
    BadgePercent,
    Banknote,
    Bell,
    Bot,
    Briefcase,
    Building,
    Building2,
    Calculator,
    CalendarCheck,
    CalendarClock,
    CalendarDays,
    ChartColumn,
    ChartLine,
    Clock,
    Cog,
    Construction,
    Contact,
    FileCheck,
    FileKey,
    FileMinus,
    FileText,
    Gauge,
    GitBranch,
    Globe,
    Handshake,
    HardHat,
    House,
    IdCard,
    KeyRound,
    Landmark,
    Layers,
    Library,
    LifeBuoy,
    ListTodo,
    Megaphone,
    MessageCircle,
    Network,
    Newspaper,
    Package,
    RadioTower,
    Receipt,
    Repeat,
    Route,
    ScrollText,
    Search,
    Settings,
    ShieldCheck,
    ShieldPlus,
    Signature,
    Sparkles,
    SquareCheck,
    Trophy,
    Truck,
    Undo2,
    UsersRound,
    Warehouse,
    Wrench,
} from '@lucide/vue';
import type { Component } from 'vue';
import type { NavIcon } from '@/lib/navigation';

export const NAV_ICONS: Record<NavIcon, Component> = {
    home: House,
    search: Search,
    notifications: Bell,
    chat: MessageCircle,
    leads: UsersRound,
    contacts: Contact,
    matchmaker: Sparkles,
    listings: Building,
    inventory: Warehouse,
    owners: Briefcase,
    offPlan: Construction,
    secondary: Repeat,
    reservations: CalendarCheck,
    deals: Handshake,
    handovers: KeyRound,
    leasing: FileKey,
    commission: BadgePercent,
    allocation: Route,
    performance: Trophy,
    marketing: Megaphone,
    portalListings: Globe,
    portalSubscriptions: Layers,
    portalInvoicing: Receipt,
    costing: Calculator,
    accounting: Landmark,
    cheques: Banknote,
    receivables: FileText,
    payables: FileMinus,
    refunds: Undo2,
    bank: ArrowLeftRight,
    propertyPerformance: ChartLine,
    ownerStatements: ScrollText,
    procurement: Package,
    maintenance: Wrench,
    preventive: CalendarClock,
    helpdesk: LifeBuoy,
    amc: ShieldPlus,
    parts: Cog,
    projects: HardHat,
    fleet: Truck,
    operations: Gauge,
    reports: ChartColumn,
    scheduled: Clock,
    approvals: SquareCheck,
    tasks: ListTodo,
    viewings: CalendarDays,
    signatures: Signature,
    complianceDocuments: FileCheck,
    hr: IdCard,
    reportCentre: Library,
    gaim: ShieldCheck,
    bulletins: Newspaper,
    leadGateway: RadioTower,
    followUp: Bot,
    pipelines: GitBranch,
    hierarchy: Network,
    organization: Building2,
    settings: Settings,
};
